name: Use Variables and Secrets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use variables
        env:
          DB_USER: ${{ vars.ASWIN_USER1412 }}
        run: |
          echo "Username is $DB_USER"

      - name: Use secrets
        env:
          DB.USERNAME: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "Password length is ${#DB_PASSWORD}"
