name: Use Variables and Secrets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use variables
        env:
          DB_USERNAME: ${{ vars.ASWIN_USER1412 }}
        run: |
          echo "Username is $ASWIN_USER1412"

      - name: Use secret
        run: |
          echo "Username is ${{ secrets.DB_USER }}"
          echo "Password length is ${#DB_PASSWORD}"
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
